spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmetic_shop
    username: root
    password: QWERTasdfzxcv271828
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
