spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmetic_shop
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: pd271828@gmail.com
    password: QWERTasdfzxcv271828
    port: 587
    protocol: smtp
    properties:
