spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmetic_shop?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/production, classpath:db/migration/develop

cron:
   expression: 1 * * * * ?